import latfun.square
#import lattices._util
#import lattices.chain
#import lattices.cubic
#import lattices.triangular
#import lattices.lieb
#import lattices.dice
#import lattices.chain_finite
#import lattices.square_finite